title = "Errata"
baseURL = "https://sjchiass.com/"
languageCode = "en-us"
theme = ["github.com/Track3/hermit"]

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 10
rssLimit = 10  # Maximum number of items in the RSS feed.
googleAnalytics = ""
enableRobotsTXT = true

enableEmoji = true

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:section/:filename/"

[author]
  name = "Sebastien Chiasson"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  # Theme color
  themeColor = "#494f5c"
  # Hermit
  relatedPosts = true
  code_copy_button = true
  # Other
  description = "Various things."
  customCSS = ["/css/accordion.css", "/css/collapsible.css"]
  
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/sjchiass"

  [[params.social]]
    name = "github"
    url = "https://github.com/sjchiass"

  [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCcogaNQW-pBUFz6G5kKCFsA"

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/sjchiass"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 20

  [[menu.main]]
    name = "Subscribe"
    url = "subscribe/"
    weight = 30
