title = "Errata"
baseURL = "https://sjchiass.com/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/bathcat.png"
  site_logo = "/images/bathcat.png"
  description = "Various things."
  facebook = "https://www.facebook.com/sjchiass"
  twitter = "https://twitter.com/sjchiass"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCcogaNQW-pBUFz6G5kKCFsA"
  github = "https://github.com/sjchiass"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  reddit = "https://www.reddit.com/user/sjchiass"
  rss = "/index.xml"
  background_color_class = "bg-black"
  recent_posts_number = 5
  show_reading_time = true
